[workspace]
members = [
    "src/cli",
    "src/codegen",
    "src/core",
    "src/macros",
    "src/toasty",

    # Driver implementations
    "src/db/ddb",
    "src/db/sqlite",

    # General utilities.
    "src/std-util",

    # Examples
    "examples/composite-key",
    "examples/hello-toasty",
    "examples/cratehub",
    "examples/user-has-one-profile",

    # Tests
    "tests/client",
]

resolver = "2"
